CREATE TABLE [ods].[NCR_Stock]
(
[ETL__ID] [int] NOT NULL IDENTITY(1, 1),
[ETL__Source] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ETL__CreatedDate] [datetime] NOT NULL,
[ETL__UpdatedDate] [datetime] NOT NULL,
[ETL__DeltaHashKey] [binary] (32) NULL,
[ID] [bigint] NULL,
[Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShortDescription] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLU] [bigint] NULL,
[Barcode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroupID] [bigint] NULL,
[CategoryID] [bigint] NULL,
[StockType] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Size] [decimal] (18, 6) NULL,
[SizeMeasureID] [bigint] NULL,
[DefaultSupplierID] [bigint] NULL,
[DS_SupplierID] [bigint] NULL,
[DS_SupplierCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS_SupplyUnitCost] [decimal] (18, 6) NULL,
[DS_SupplyUnitID] [bigint] NULL,
[DS_SupplyUnitType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS_SupplyUnitBaseQty] [decimal] (18, 6) NULL,
[DS_SupplyUnitTransferQty] [decimal] (18, 6) NULL,
[DS_OrderUnitQty] [decimal] (18, 6) NULL,
[BaseUnitID] [bigint] NULL,
[TransferUnitID] [bigint] NULL,
[TransferUnitBaseQty] [decimal] (18, 6) NULL,
[StockUnitID] [bigint] NULL,
[StockUnitBaseQty] [decimal] (18, 6) NULL,
[SellingUnitType] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Saleable] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StringPLU] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OpenPrice] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NonDimminish] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Normal] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Base] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeableItemID] [bigint] NULL,
[ChargeableParentID] [bigint] NULL,
[ChargeableRecipeID] [bigint] NULL,
[TotalQuantityOnOrder] [decimal] (18, 6) NULL,
[ReorderLevel] [decimal] (18, 6) NULL,
[CriticalFactor] [decimal] (18, 6) NULL,
[Notes] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaseUnitAverageCost] [decimal] (18, 6) NULL,
[BaseUnitCurrentCost] [decimal] (18, 6) NULL,
[PriceLevel01] [decimal] (18, 6) NULL,
[PriceLevel02] [decimal] (18, 6) NULL,
[PriceLevel03] [decimal] (18, 6) NULL,
[PriceLevel04] [decimal] (18, 6) NULL,
[PriceLevel05] [decimal] (18, 6) NULL,
[PriceLevel06] [decimal] (18, 6) NULL,
[PriceLevel07] [decimal] (18, 6) NULL,
[PriceLevel08] [decimal] (18, 6) NULL,
[PriceLevel09] [decimal] (18, 6) NULL,
[PriceLevel10] [decimal] (18, 6) NULL,
[SaleableGLCodeID] [bigint] NULL,
[SuppliedGLCodeID] [bigint] NULL,
[CouponGrossValue] [decimal] (18, 6) NULL,
[CoupenNetValue] [decimal] (18, 6) NULL,
[IsLocked] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDeleted] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupplierTaxExempt] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataInputUnitType] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GraphicPath] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExcludedSuiteServiceCharge] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaseUnitAverageExpensesCost] [decimal] (18, 6) NULL,
[DontPrintBarcode] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RetailID] [bigint] NULL,
[StyleID] [bigint] NULL,
[ColourID] [bigint] NULL,
[PLUNotes] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DepartmentID] [bigint] NULL,
[TotalQuantityOnHand] [decimal] (18, 6) NULL,
[KeypadGraphicID] [bigint] NULL,
[ProductionGroupSizeID] [bigint] NULL,
[ProductionDefaultWastage] [decimal] (18, 6) NULL,
[ProductionCutSize] [decimal] (18, 6) NULL,
[NonDiminish] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CouponNetValue] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [ods].[NCR_Stock] ADD CONSTRAINT [PK_ods__Stock] PRIMARY KEY NONCLUSTERED  ([ETL__ID])
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_ods__Stock] ON [ods].[NCR_Stock]
GO
CREATE NONCLUSTERED INDEX [IX_Key] ON [ods].[NCR_Stock] ([ID]) INCLUDE ([ETL__DeltaHashKey])
GO
