CREATE TABLE [stg].[NCR_Stock]
(
[ETL__ID] [bigint] NOT NULL IDENTITY(1, 1),
[ETL__CreatedDate] [datetime] NOT NULL,
[ETL__Source] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ETL__DeltaHashKey] [binary] (32) NULL,
[ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShortDescription] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Barcode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroupID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Size] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SizeMeasureID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultSupplierID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS_SupplierID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS_SupplierCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS_SupplyUnitCost] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS_SupplyUnitID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS_SupplyUnitType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS_SupplyUnitBaseQty] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS_SupplyUnitTransferQty] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS_OrderUnitQty] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaseUnitID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransferUnitID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransferUnitBaseQty] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockUnitID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockUnitBaseQty] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SellingUnitType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Saleable] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StringPLU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OpenPrice] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NonDimminish] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Normal] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Base] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeableItemID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeableParentID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeableRecipeID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalQuantityOnOrder] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReorderLevel] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CriticalFactor] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Notes] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaseUnitAverageCost] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaseUnitCurrentCost] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceLevel01] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceLevel02] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceLevel03] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceLevel04] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceLevel05] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceLevel06] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceLevel07] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceLevel08] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceLevel09] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriceLevel10] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SaleableGLCodeID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SuppliedGLCodeID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CouponGrossValue] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoupenNetValue] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsLocked] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDeleted] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupplierTaxExempt] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataInputUnitType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GraphicPath] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExcludedSuiteServiceCharge] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaseUnitAverageExpensesCost] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DontPrintBarcode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RetailID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StyleID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ColourID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLUNotes] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DepartmentID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalQuantityOnHand] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KeypadGraphicID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductionGroupSizeID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductionDefaultWastage] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductionCutSize] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NonDiminish] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CouponNetValue] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [stg].[NCR_Stock] ADD CONSTRAINT [PK_stg__Stock] PRIMARY KEY NONCLUSTERED  ([ETL__ID])
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_stg__Stock] ON [stg].[NCR_Stock]
GO
