CREATE TABLE [stg].[NCR_Department]
(
[ETL__ID] [bigint] NOT NULL IDENTITY(1, 1),
[ETL__CreatedDate] [datetime] NOT NULL,
[ETL__Source] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ETL__DeltaHashKey] [binary] (32) NULL,
[ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDeleted] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrganizationID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IPAddress] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultLocationID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultKeypadID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxLevel01] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxLevel02] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxLevel03] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxLevel04] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastIPAddress] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CountryID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnlineAccess] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WeeklyTakingsTypeID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LogicalID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverrideSupplierTax] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupplierTax] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrintMovements] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrintClockOn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrintClockOff] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrintBreakOn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrintBreakOff] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BudgetTemplateID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SundayRosterTypeID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MondayRosterTypeID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TuesdayRosterTypeID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WednesdayRosterTypeID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThursdayRosterTypeID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FridayRosterTypeID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SaturdayRosterTypeID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoyaltyDisclaimer] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxLevel05] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxLevel06] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxLevel07] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxLevel08] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrintLaborOnHourly] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DailyLabourHoursRounding] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AutoLogOffTimeOut] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DashboardStockFamilyID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DashboardStockFamilyTitle] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AutoTerminalReportResetEnabled] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AutoTerminalReportResetTime] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChainCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FuseboxIP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnlyShowLocalRemotePrinters] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [stg].[NCR_Department] ADD CONSTRAINT [PK_stg__Department] PRIMARY KEY NONCLUSTERED  ([ETL__ID])
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_stg__Department] ON [stg].[NCR_Department]
GO
