CREATE TABLE [stg].[NCR_Location]
(
[ETL__ID] [bigint] NOT NULL IDENTITY(1, 1),
[ETL__CreatedDate] [datetime] NOT NULL,
[ETL__Source] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ETL__DeltaHashKey] [binary] (32) NULL,
[ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LogicalID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CopiedLogicalID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_GLDivision] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[_DeliveryAddress] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberLookupMode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataInputMode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataInputMask] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MasterTillID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MasterWorkstationID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MasterWorkstationName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransferFromLocationID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClerkMode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IdleMode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IdleDelay] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scrollable] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScrollRate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CashHigh] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShowRunningTotal] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ItemOverride] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InEscapeSequence] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OutEscapeSequence] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrintGroupHeader] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataAccount] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultPriceLevelID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockFamilyID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasWorksheet] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Retail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LongDescription] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Warehouse] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDeleted] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsVending] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsPortable] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransferFromLocationID2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnableTip] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeatAssignmentID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportGroupID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PromoItemID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextParameters] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastSaleDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompulsoryPriceLevels] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrintStandsheet] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrinkMode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrinkRuleID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrinkDailyLimit] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrinkHourlyLimit] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ForcedPLUs] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverrideRounding] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RoundingMode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RoundingAmount] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventTypeID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsSuiteCatering] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrinkSaleLimit] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrintPLU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MasterTillLogicalID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MerchantID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tokens] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CalculationType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DepartmentID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FineDining] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Covers] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DisableAlchohol] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsBanquet] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RetailPriceLevelID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ManagerTillLogicalID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BanquetScreenDefault] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LocationLogon] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TimeOffset] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IdleTextMessageID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeaderTextMessageID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrailerTextMessageID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TableFirstMode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TableSeatMode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TableRestrictedMode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TipWarning] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TableLocking] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServiceChargeID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TableExists] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastOfflineCCProcess] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockFamilyCount] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShowRunningTotalMulti] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShowRunningTotalTouch] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerDisplayShowOfflineStatus] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserForcedPLU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserForcedPLU2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserForcedPLU3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionalPLU] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TableLayoutID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdditionalDataEscapeSequence] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnprintedTableOptions] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnprintedTableFlashPeriod] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockFamilyIDToIgnore] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DontPrintReportsWhenOpenOrders] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DisplayTableLayoutByDefault] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TablePreAuthAmount] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TableNameCCDetailsSelection] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TableNameMode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AutoAuths] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthAdjustPercent] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [stg].[NCR_Location] ADD CONSTRAINT [PK_stg__Location] PRIMARY KEY NONCLUSTERED  ([ETL__ID])
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_stg__Location] ON [stg].[NCR_Location]
GO
